# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-11 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_permissoesusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipousuario',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
    ]
