# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-18 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_permissoesusuario_excluir_formulario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissoesusuario',
            name='receber_alerta_pedidos_vistoria',
        ),
    ]
