# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-22 04:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_assinaturausuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinaturausuario',
            name='usuario',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
