# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-04 04:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Laudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_proposta', models.CharField(max_length=15)),
                ('registro_anp_definitivo', models.NullBooleanField()),
                ('registro_anp_numero', models.CharField(max_length=50, null=True)),
                ('registro_anp_data_expedicao', models.DateField(null=True)),
                ('registro_anp_data_validade', models.DateField(null=True)),
                ('alvara_funcionamento_definitivo', models.NullBooleanField()),
                ('alvara_funcionamento_numero', models.CharField(max_length=50, null=True)),
                ('alvara_funcionamento_data_expedicao', models.DateField(null=True)),
                ('alvara_funcionamento_data_validade', models.DateField(null=True)),
                ('licenca_ambiental', models.IntegerField(null=True)),
                ('licenca_ambiental_numero', models.CharField(max_length=50, null=True)),
                ('licenca_ambiental_data_expedicao', models.DateField(null=True)),
                ('licenca_ambiental_data_validade', models.DateField(null=True)),
                ('atestado_regularidade_ar_sim', models.BooleanField()),
                ('atestado_regularidade_ar_numero', models.CharField(max_length=50, null=True)),
                ('atestado_regularidade_ar_data_expedicao', models.DateField(null=True)),
                ('atestado_regularidade_ar_data_validade', models.DateField(null=True)),
                ('observacao', models.CharField(max_length=300, null=True)),
                ('venda_combustiveis_disponivel', models.BooleanField()),
                ('lavagem_viculos_disponivel', models.BooleanField()),
                ('restaurante_lanchonete_conveniencia_disponivel', models.BooleanField()),
                ('troca_oleo_disponivel', models.BooleanField()),
                ('oficina_mecanica_disponivel', models.BooleanField()),
                ('venda_gas_cozinha', models.BooleanField()),
                ('outros_servicos_disponibilidade', models.CharField(max_length=300)),
                ('valvula_retentora_vapor_disponibilidade', models.BooleanField()),
                ('valvula_retentora_vapor_estado_conservacao', models.IntegerField(null=True)),
                ('tanque_sub_parede_dupla_jaquetado', models.BooleanField()),
                ('tanque_sub_parede_data_instalacao', models.DateField(null=True)),
                ('poco_monitoramento_disponibilidade', models.BooleanField()),
                ('poco_monitoramento_estado_conservacao', models.IntegerField(null=True)),
                ('caneletas_ilhas_bombas_disponibilidade', models.BooleanField()),
                ('caneletas_ilhas_bombas_estado_conservacao', models.IntegerField(null=True)),
                ('caneletas_perimetro_disponibilidade', models.BooleanField()),
                ('caneletas_perimetro_estado_conservacao', models.IntegerField(null=True)),
                ('piso_concreto_alisado_disponibilidade', models.BooleanField()),
                ('piso_concreto_alisado_estado_conservacao', models.IntegerField(null=True)),
                ('caneletas_interligadas_sao_disponibilidade', models.BooleanField()),
                ('caneletas_interligadas_sao_estado_conservacao', models.IntegerField(null=True)),
                ('sistema_deteccao_vazamento_disponibilidade', models.BooleanField()),
                ('sistema_deteccao_vazamento_estado_conservacao', models.IntegerField(null=True)),
                ('area_lavagem_piso_can_sao_disponibilidade', models.BooleanField()),
                ('area_lavagem_piso_can_sao_estado_conservacao', models.IntegerField(null=True)),
                ('area_troca_oleo_piso_can_sao_disponibilidade', models.BooleanField()),
                ('area_troca_oleo_piso_can_sao_estado_conservacao', models.IntegerField(null=True)),
                ('area_armazenamento_residuos_coberta_piso_disponibilidade', models.BooleanField()),
                ('area_armazenamento_residuos_coberta_piso_estado_conservacao', models.IntegerField(null=True)),
                ('atendido_rede_publica_saneamento', models.BooleanField()),
                ('quantidade_tanques', models.IntegerField(null=True)),
                ('capacidade_armazenamento', models.IntegerField(default=0)),
                ('houve_sinistro_ultimos_anos', models.BooleanField()),
                ('prejuizo_estimativa', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('data_sinistro', models.DateField(null=True)),
                ('ocorrencia', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='laudo',
            name='posto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='formulario_vistoria.Posto'),
        ),
        migrations.AddField(
            model_name='laudo',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foto',
            name='laudo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='formulario_vistoria.Laudo'),
        ),
    ]
