# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-06 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_vistoria', '0002_auto_20160806_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
