# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-07 22:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_vistoria', '0003_laudo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudo',
            name='area_armazenamento_residuos_coberta_piso_disponibilidade',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='area_lavagem_piso_can_sao_disponibilidade',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='area_troca_oleo_piso_can_sao_disponibilidade',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='atendido_rede_publica_saneamento',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='atestado_regularidade_ar_sim',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='caneletas_ilhas_bombas_disponibilidade',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='caneletas_interligadas_sao_disponibilidade',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='caneletas_perimetro_disponibilidade',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='houve_sinistro_ultimos_anos',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='lavagem_viculos_disponivel',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='oficina_mecanica_disponivel',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='outros_servicos_disponibilidade',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='piso_concreto_alisado_disponibilidade',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='poco_monitoramento_disponibilidade',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='restaurante_lanchonete_conveniencia_disponivel',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='sistema_deteccao_vazamento_disponibilidade',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='tanque_sub_parede_dupla_jaquetado',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='troca_oleo_disponivel',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='usuario',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='valvula_retentora_vapor_disponibilidade',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='venda_combustiveis_disponivel',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='venda_gas_cozinha',
            field=models.NullBooleanField(),
        ),
    ]
