# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-07 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_vistoria', '0005_tipousuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipousuario',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
    ]
