# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-09 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_vistoria', '0006_auto_20160907_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='endereco_pdf',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
